version: "3.1"

secrets:
  certbot_email:
    file: ./secrets/certbot_email.txt

networks:
  default:
  nginx_main:
    external: true

services:

    nginx:
        build: ./nginx_container/
        volumes:
          - ./nginx_container/logs:/etc/nginx/logs/
          - ./www:/www/
        networks:
          default:
          nginx_main:
            ipv4_address: 172.16.0.5
        environment:
          CERTBOT_EMAIL: /run/secrets/certbot_email
        secrets:
         - source: certbot_email
        restart: unless-stopped
